# Generated by Django 4.2 on 2025-08-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="restaurants/"),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
