# Generated by Django 4.2 on 2025-08-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="category",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
