# Generated by Django 4.2 on 2025-08-25 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0001_initial"),
        ("orders", "0002_order_restaurant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="restaurants.restaurant",
            ),
        ),
    ]
